Repository gnims-project/GNIMS-backend, pull requests merged in 2023-02, with the labels that each got.

#1 project settings
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/gnims/project/ProjectApplication.java
  src/main/java/com/gnims/project/domain/member/entity/Member.java
  src/main/resources/application.properties
  src/test/java/com/gnims/project/ProjectApplicationTests.java
  src/test/resources/application.properties
Labels: enhancement

#2 Feat/first
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: feature

#7 Feat/cicd
  .ebextensions/00-makeFiles.config
  .ebextensions/00-set-timezone.config
  .github/workflows/gradle.yml
  .platform/nginx/nginx.conf
  Procfile
  build.gradle
Labels: feature

#8 Fix #5 CI/CD 스크립트 수정
  .github/workflows/gradle.yml
Labels: feature

#9 Feat/signup
  src/main/java/com/gnims/project/domain/member/entity/Member.java
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/MessageResponseDto.java
  src/main/java/com/gnims/project/domain/user/dto/SignupRequestDto.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#11 Feat/security
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
  src/main/java/com/gnims/project/security/user/UserDetailsImpl.java
  src/main/java/com/gnims/project/security/user/UserDetailsServiceImpl.java
Labels: feature

#13 Feat/jwt
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
  src/main/java/com/gnims/project/security/jwt/JwtAuthFilter.java
  src/main/java/com/gnims/project/security/jwt/JwtUtil.java
Labels: feature

#14 Feat #12 SecurityExceptionDto 추가
  src/main/java/com/gnims/project/security/jwt/SecurityExceptionDto.java
Labels: feature

#16 Feat #3 로그인
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/LoginRequestDto.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#18 Feat/social login
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/kakao/KakaoService.java
  src/main/java/com/gnims/project/domain/user/kakao/KakaoUserInfoDto.java
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#19 Feat/base entity
  src/main/java/com/gnims/project/config/JpaConfig.java
  src/main/java/com/gnims/project/domain/follow/controller/HealthCheckController.java
  src/main/java/com/gnims/project/util/Auditor.java
  src/main/java/com/gnims/project/util/BaseEntity.java
  src/main/java/com/gnims/project/util/TimeStamped.java
Labels: feature

#20 fix #17 카카오 로그인 redirect_uri 수정
  src/main/java/com/gnims/project/domain/user/kakao/KakaoService.java
Labels: bug

#26 Feat/friendship
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/controller/HealthCheckController.java
  src/main/java/com/gnims/project/domain/friendship/dto/FollowResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FollowingResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResult.java
  src/main/java/com/gnims/project/domain/friendship/entity/FollowStatus.java
  src/main/java/com/gnims/project/domain/friendship/entity/Friendship.java
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
Labels: feature, test-code

#28 Fix/login
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/LoginResponseDto.java
  src/main/java/com/gnims/project/domain/user/kakao/KakaoService.java
  src/main/java/com/gnims/project/domain/user/naver/NaverService.java
Labels: enhancement

#30 Feat/friendship
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/entity/Friendship.java
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
Labels: feature

#31 Fix/login
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: enhancement

#32 Bug #27 import 추가
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
Labels: bug

#33 Feat/friendship
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/entity/Friendship.java
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
Labels: feature, test-code

#35 Feat #34 예외 처리
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
Labels: feature

#36 Fix #34 예외 처리 DTO
  src/main/java/com/gnims/project/exception/dto/ExceptionResponseListMessage.java
  src/main/java/com/gnims/project/exception/dto/ExceptionResponseMessage.java
Labels: feature

#38 Refactor #37 패키지 구조 변경
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/entity/SocialCode.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/security/jwt/JwtUtil.java
  src/main/java/com/gnims/project/security/service/UserDetailsImpl.java
  src/main/java/com/gnims/project/security/service/UserDetailsServiceImpl.java
  src/main/java/com/gnims/project/social/controller/SocialLoginController.java
  src/main/java/com/gnims/project/social/dto/SocialCodeDto.java
  src/main/java/com/gnims/project/social/dto/SocialProfileDto.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
  src/main/java/com/gnims/project/util/Auditor.java
Labels: refactor

#42 Feat/signup
  build.gradle
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/SignupRequestDto.java
  src/main/java/com/gnims/project/social/controller/SocialLoginController.java
  src/main/java/com/gnims/project/util/validation/ValidationGroups.java
  src/main/java/com/gnims/project/util/validation/ValidationSequence.java
Labels: feature

#43 Feat/paging-read
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipPageableResult.java
  src/main/java/com/gnims/project/domain/friendship/dto/PageDto.java
  src/main/java/com/gnims/project/domain/friendship/dto/PageRequestDto.java
  src/main/java/com/gnims/project/domain/friendship/dto/PagingDataResponse.java
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
Labels: feature, fix

#44 Feat #4 비밀번호 암호화
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#46 Fix #45 로그인시 비밀번호를 암호화한 후 비교
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: fix

#47 Feat #21 네이버 로그인 Client와 연동
  src/main/java/com/gnims/project/social/controller/SocialLoginController.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
Labels: feature

#48 Feat/event
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/event/repository/EventRepository.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/SimpleScheduleResult.java
  src/main/java/com/gnims/project/domain/schedule/entity/Schedule.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/util/embedded/Appointment.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleServiceTest.java
Labels: feature, test-code

#49 Fix #40 수정 누락된 파일 커밋
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleForm.java
Labels: fix

#50 Feat/event
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleForm.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleServiceTest.java
Labels: feature

#52 Feat/signup
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/EmailDto.java
  src/main/java/com/gnims/project/domain/user/dto/LoginRequestDto.java
  src/main/java/com/gnims/project/domain/user/dto/NicknameDto.java
  src/main/java/com/gnims/project/domain/user/dto/SignupRequestDto.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/security/jwt/JwtAuthFilter.java
  src/main/java/com/gnims/project/security/jwt/JwtUtil.java
  src/main/java/com/gnims/project/security/service/UserDetailsImpl.java
  src/main/java/com/gnims/project/security/service/UserDetailsServiceImpl.java
Labels: feature

#54 Feat/schedule-read
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllUserDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneUserDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadScheduleResult.java
  src/main/java/com/gnims/project/domain/schedule/entity/Schedule.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
Labels: feature

#56 fix #55
  src/main/java/com/gnims/project/domain/friendship/dto/FollowingResponse.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleServiceTest.java
Labels: fix

#59 Test/schedule
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllUserDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneUserDto.java
  src/main/java/com/gnims/project/domain/schedule/entity/Schedule.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: test-code, fix

#64 Feat/profile update
  build.gradle
  src/main/java/com/gnims/project/config/AwsS3Config.java
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/LoginRequestDto.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#63 Feat #3 필요없는 socialCode 삭제
  src/main/java/com/gnims/project/domain/user/dto/LoginRequestDto.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#69 Test/schedule
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneResponse.java
  src/main/java/com/gnims/project/domain/schedule/entity/Schedule.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: test-code, fix

#73 Feat #67 유저 검색 추가
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/SearchResponseDto.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#75 Feat/schedule-delete
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/event/repository/EventRepository.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
Labels: feature

#76 Fix #74 확장자 제한하기
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: fix

#78 Feat/schedule-update
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/gnims/project/util/embedded/Appointment.java
Labels: feature

#79 Fix/schedule update
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/UpdateForm.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
Labels: fix

#80 Fix #66 스케줄 등록 API 테스트 케이스 수정
  src/main/java/com/gnims/project/security/exception/CustomAuthenticationEntryPoint.java
Labels: fix

#81 Fix #66 스케줄 등록 API 테스트 케이스 수정
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
Labels: fix

#82 Feat/past-schedule
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadPastAllResponse.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/security/service/UserDetailsImpl.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: feature

#83 Feat #40 스케줄 생성 API 수정
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
Labels: feature

#84 Feat #4 에러 리턴 방식 변경
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#88 bug #87 cors 허용할 헤드 명시
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
Labels: fix

#86 Feat/user search
  build.gradle
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/LoginResponseDto.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/security/service/UserDetailsImpl.java
  src/main/java/com/gnims/project/security/service/UserDetailsServiceImpl.java
  src/main/java/com/gnims/project/social/dto/SocialLoginDto.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: feature

#89 bug #87 cors 이슈 해결
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
Labels: fix

#90 Feat #67 api 수정
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
Labels: refactor

#93 Feat/schedule
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/friendship/entity/Friendship.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/entity/Schedule.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: feature, test-code

#95 Refactor/user
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/LoginResponseDto.java
  src/main/java/com/gnims/project/domain/user/dto/MessageResponseDto.java
  src/main/java/com/gnims/project/domain/user/dto/SearchPageableResult.java
  src/main/java/com/gnims/project/domain/user/dto/SimpleMessageResult.java
  src/main/java/com/gnims/project/domain/user/dto/UserResult.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/security/service/UserDetailsServiceImpl.java
  src/main/java/com/gnims/project/social/controller/SocialLoginController.java
  src/main/java/com/gnims/project/social/dto/SocialEmailDto.java
  src/main/java/com/gnims/project/social/dto/SocialEmailNicknameDto.java
  src/main/java/com/gnims/project/social/dto/SocialLoginDto.java
  src/main/java/com/gnims/project/social/dto/SocialResult.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: refactor

#96 Bug #87 cors 설정 변경
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
Labels: fix

#97 Feat/profile update
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: feature

#101 Test/schedule
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleDeleteTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleUpdateReadTest.java
Labels: test-code

#102 Feat/schedule
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/EventOneQueryDto.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
Labels: feature

#103 Feat/schedule
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/EventAllQueryDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/UpdateForm.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
Labels: feature

#108 Feat/testcode
  .github/workflows/gradle.yml
  src/main/java/com/gnims/project/exception/dto/ExceptionResponseListMessage.java
  src/test/java/com/gnims/project/domain/user/service/ImageUploadTest.java
  src/test/java/com/gnims/project/domain/user/service/SocialSignupTest.java
  src/test/java/com/gnims/project/domain/user/service/UserLoginTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSearchTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSignupTest.java
  src/test/resources/image/르탄이.png
  src/test/resources/image/어쩌구저쩌구.abcde
Labels: test-code

#109 Chore #5 빌드 스크립트 수정
  .github/workflows/gradle.yml
Labels: fix

#113 Feat/event
  src/main/java/com/gnims/project/ProjectApplication.java
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/event/repository/EventRepository.java
  src/main/java/com/gnims/project/domain/schedule/dto/EventAllQueryDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/EventOneQueryDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneResponse.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/scheduler/EventScheduler.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleDeleteTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleUpdateReadTest.java
Labels: feature, test-code

#115 Feat #114 알람 기능 프로토 타입 추가
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/gnims/project/domain/notification/entity/AlarmType.java
  src/main/java/com/gnims/project/domain/notification/entity/Notification.java
  src/main/java/com/gnims/project/domain/notification/repository/EmitterRepository.java
  src/main/java/com/gnims/project/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/gnims/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/domain/notification/util/AlarmTime.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
Labels: feature

#116 Revert "Feat #114 알람 기능 프로토 타입 추가"
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/gnims/project/domain/notification/entity/AlarmType.java
  src/main/java/com/gnims/project/domain/notification/entity/Notification.java
  src/main/java/com/gnims/project/domain/notification/repository/EmitterRepository.java
  src/main/java/com/gnims/project/domain/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/gnims/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/domain/notification/util/AlarmTime.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
Labels: feature

#118 Feat/notification
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleCreateController.java
  src/main/java/com/gnims/project/scheduler/EventScheduler.java
  src/main/java/com/gnims/project/util/Auditor.java
Labels: feature

#119 Feat/login
  src/main/java/com/gnims/project/domain/user/dto/LoginResponseDto.java
  src/main/java/com/gnims/project/domain/user/entity/SocialCode.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/social/dto/SocialEmailNicknameDto.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
Labels: feature

#120 Feat #17 소셜 회원가입 누락 부분 수정
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#121 Feat #17 소셜 회원가입 누락 부분 수정
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#122 Feat #3 회원가입 누락 부분 수정
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#124 Feat/password reset
  build.gradle
  src/main/java/com/gnims/project/config/EmailConfig.java
  src/main/java/com/gnims/project/domain/user/NicknameEmailDto.java
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/LoginResponseDto.java
  src/main/java/com/gnims/project/domain/user/dto/PasswordDto.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
  src/main/java/com/gnims/project/util/gmail/EmailController.java
  src/main/java/com/gnims/project/util/gmail/EmailPasswordDto.java
  src/main/java/com/gnims/project/util/gmail/EmailRepository.java
  src/main/java/com/gnims/project/util/gmail/EmailServiceImpl.java
  src/main/java/com/gnims/project/util/gmail/EmailValidation.java
  src/test/java/com/gnims/project/domain/user/service/PasswordUpdateTest.java
Labels: feature

#125 Feat #123 테스트 코드, 메소드 명 업데이트
  src/main/java/com/gnims/project/util/gmail/EmailController.java
  src/test/java/com/gnims/project/domain/user/service/PasswordUpdateTest.java
Labels: feature

#128 Feat/password-reset
  src/main/java/com/gnims/project/domain/user/dto/PasswordDto.java
  src/main/java/com/gnims/project/domain/user/dto/SignupRequestDto.java
Labels: feature

#129 Feat #3 로그인 리스폰스 이메일 수정
  src/main/java/com/gnims/project/domain/user/dto/LoginResponseDto.java
  src/main/java/com/gnims/project/domain/user/entity/SocialCode.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/test/java/com/gnims/project/domain/user/service/PasswordUpdateTest.java
Labels: feature

#130 Feat #4 회원가입 테스트 코드 수정
  src/test/java/com/gnims/project/domain/user/service/UserSignupTest.java
Labels: feature

#131 Feat/schedule-read
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
Labels: feature, test-code

#132 Feat/schedule read
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
Labels: refactor

#134 Feat/user search
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/SearchResponseDto.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/test/java/com/gnims/project/domain/user/service/UserSearchTest.java
Labels: feature

#135 Feat/password reset
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/util/gmail/EmailController.java
  src/main/java/com/gnims/project/util/gmail/EmailPasswordDto.java
  src/main/java/com/gnims/project/util/gmail/EmailServiceImpl.java
Labels: feature

#139 Feat/friendship
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/dto/FollowReadResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FollowResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResponse.java
  src/main/java/com/gnims/project/domain/friendship/entity/Friendship.java
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
Labels: feature

#138 Refactor/message
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/NicknameEmailDto.java
  src/main/java/com/gnims/project/domain/user/dto/SignupRequestDto.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/exception/dto/ExceptionMessage.java
  src/main/java/com/gnims/project/security/jwt/JwtAuthFilter.java
  src/main/java/com/gnims/project/security/jwt/JwtUtil.java
  src/main/java/com/gnims/project/social/dto/SocialSignupDto.java
  src/main/java/com/gnims/project/util/ResponseMessage.java
  src/test/java/com/gnims/project/domain/user/service/ImageUploadTest.java
  src/test/java/com/gnims/project/domain/user/service/PasswordUpdateTest.java
  src/test/java/com/gnims/project/domain/user/service/SocialSignupTest.java
  src/test/java/com/gnims/project/domain/user/service/UserLoginTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSearchTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSignupTest.java
Labels: refactor

#140 Feat #3 로그인 리턴 값 수정
  src/main/java/com/gnims/project/domain/user/dto/LoginResponseDto.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/util/ResponseMessage.java
Labels: feature

#141 Feat #22 팔로워 조회 API 최적화
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
Labels: feature

#142 Fix #22 import 추가
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
Labels: feature

#145 Feat #144 알림 기능 프로토 타입 추가
  src/main/java/com/gnims/project/config/AsyncConfig.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleCreateController.java
Labels: feature

#146 Feat #17 소셜 로그인 수정 - body로 받기
  src/main/java/com/gnims/project/social/controller/SocialLoginController.java
  src/main/java/com/gnims/project/social/dto/SocialTokenDto.java
Labels: feature

#148 Refactor #137 응답, 예외 메시지 상수화
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleCreateController.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/exception/dto/ExceptionMessage.java
  src/main/java/com/gnims/project/util/ResponseMessage.java
Labels: feature

#149 Refactor #137 테스트 코드 수정
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleDeleteTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleUpdateReadTest.java
Labels: refactor

#150 Feat/password reset
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/AuthEmailDto.java
  src/main/java/com/gnims/project/domain/user/dto/EmailDto.java
  src/main/java/com/gnims/project/domain/user/dto/NicknameDto.java
  src/main/java/com/gnims/project/domain/user/dto/NicknameEmailDto.java
  src/main/java/com/gnims/project/domain/user/dto/PasswordDto.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/exception/dto/ExceptionMessage.java
  src/main/java/com/gnims/project/util/ResponseMessage.java
  src/main/java/com/gnims/project/util/gmail/AuthCodeDto.java
  src/main/java/com/gnims/project/util/gmail/EmailController.java
  src/main/java/com/gnims/project/util/gmail/EmailPasswordDto.java
  src/main/java/com/gnims/project/util/gmail/EmailRepository.java
  src/main/java/com/gnims/project/util/gmail/EmailServiceImpl.java
  src/main/java/com/gnims/project/util/gmail/EmailValidation.java
Labels: feature

#151 Feat/schedule
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/SchedulePastTest.java
Labels: feature, test-code

#152 Feat #144 일정 초대 시 알림 보내는 방식 변경
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
Labels: feature

#153 Feat #51 일정 전체 조회 페이징 API 수정 - 프로토 타입
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/EventAllQueryDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/PageableReadScheduleResult.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
Labels: feature

#154 Feat/schedule
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/PageableReadResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadPendingDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadPendingResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/info
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/SchedulePastTest.java
Labels: feature

#155 Feat #60 Pending 일정 조회 API 수정
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
Labels: feature, fix

#156 Feat #67 jpql 적용 검색 최적화
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/SearchAllQueryDto.java
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/test/java/com/gnims/project/domain/user/service/UserSignupTest.java
Labels: feature

#157 Feat #67 누락 파일 업로드
  src/test/java/com/gnims/project/domain/user/service/SocialSignupTest.java
Labels: feature

#158 Feat #144 Nofitcation 프로토타입 개발
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/entity/Notification.java
  src/main/java/com/gnims/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleCreateController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleForm.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleServiceForm.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/util/embedded/Appointment.java
Labels: feature

#161 Feat #144 강제 병합, 프론트와 테스트 중
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
Labels: feature

#163 Feat #144 강제 병합, 프론트와 테스트 중
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
Labels: feature

#168 Refactor #167 프로젝트 패키지 구조 변경
  .platform/nginx/nginx.conf
  src/main/java/com/gnims/project/config/JpaConfig.java
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/entity/Friendship.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/notification/entity/Notification.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleCreateController.java
  src/main/java/com/gnims/project/domain/schedule/entity/Schedule.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/EmailDto.java
  src/main/java/com/gnims/project/domain/user/dto/NicknameDto.java
  src/main/java/com/gnims/project/domain/user/dto/PasswordDto.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/log/advice/LogAspect.java
  src/main/java/com/gnims/project/log/entity/Log.java
  src/main/java/com/gnims/project/log/repository/LogRepository.java
  src/main/java/com/gnims/project/scheduler/EventScheduler.java
  src/main/java/com/gnims/project/security/jwt/JwtAuthFilter.java
  src/main/java/com/gnims/project/security/jwt/JwtUtil.java
  src/main/java/com/gnims/project/share/gmail/AuthCodeDto.java
  src/main/java/com/gnims/project/share/gmail/EmailController.java
  src/main/java/com/gnims/project/share/gmail/EmailPasswordDto.java
  src/main/java/com/gnims/project/share/gmail/EmailRepository.java
  src/main/java/com/gnims/project/share/gmail/EmailServiceImpl.java
  src/main/java/com/gnims/project/share/gmail/EmailValidation.java
  src/main/java/com/gnims/project/share/message/ExceptionMessage.java
  src/main/java/com/gnims/project/share/message/ResponseMessage.java
  src/main/java/com/gnims/project/share/persistence/embedded/Appointment.java
  src/main/java/com/gnims/project/share/persistence/superclass/Auditor.java
  src/main/java/com/gnims/project/share/persistence/superclass/BaseEntity.java
  src/main/java/com/gnims/project/share/persistence/superclass/TimeStamped.java
  src/main/java/com/gnims/project/share/validation/ValidationGroups.java
  src/main/java/com/gnims/project/share/validation/ValidationSequence.java
  src/main/java/com/gnims/project/social/dto/SocialSignupDto.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleDeleteTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleUpdateReadTest.java
  src/test/java/com/gnims/project/domain/user/service/ImageUploadTest.java
  src/test/java/com/gnims/project/domain/user/service/PasswordUpdateTest.java
  src/test/java/com/gnims/project/domain/user/service/SocialSignupTest.java
  src/test/java/com/gnims/project/domain/user/service/UserLoginTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSearchTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSignupTest.java
Labels: refactor

#169 Refactor #167 프로젝트 패키지 구조 변경
  src/main/java/com/gnims/project/domain/user/dto/SignupRequestDto.java
Labels: refactor

#171 Feat/password reset
  src/main/java/com/gnims/project/share/gmail/EmailRepository.java
Labels: feature

#172 Test #68 수락/거절 대기중인 스케줄 조회 API 테스트 케이스 작성
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/SchedulePendingTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleRejectTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleUpdateReadTest.java
Labels: test-code

#174 Feat/notification
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendShipServiceResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResponse.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/entity/Notification.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
Labels: feature

#176 Refactor #175 도메인 구조 변경
  src/main/java/com/gnims/project/domain/event/controller/EventController.java
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/event/service/EventService.java
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleCreateController.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
Labels: refactor

#177 Feat #67 유저 검색 임시 조치
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#178 Feat #67 유저 검색 임시 조치 수정
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#180 Feat #62 프로필 업데이트 리턴 값 변경
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/ProfileImageDto.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: feature

#179 Feat/schedule
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/PageableReadResponse.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: feature, test-code

#181 Feat/jwt exception
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
  src/main/java/com/gnims/project/security/exception/CustomAuthenticationEntryPoint.java
Labels: feature

#183 Refactor #182 DB 이미지 저장 값 변경
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: refactor

#186 Feat/friendship
  build.gradle
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
Labels: feature

#185 Feat #184 코드 분석 라이브러리 jacoco 의존성 추가
  build.gradle
Labels: feature

#189 Fix/schedule
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/PageableReadResponse.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/security/jwt/JwtAuthFilter.java
  src/test/java/com/gnims/project/authorization/JwtAuthTest.java
Labels: bug, fix

#190 Feat #57 일정 전체 조회 API 정렬 기능 추가
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
Labels: feature

#192 Feat/social login
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/entity/User.java
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/social/controller/SocialLoginController.java
Labels: feature

#194 Feat/slack
  build.gradle
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipPageableResult.java
  src/main/java/com/gnims/project/domain/friendship/dto/PageDto.java
  src/main/java/com/gnims/project/domain/friendship/dto/PageRequestDto.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadPastAllResponse.java
  src/main/java/com/gnims/project/domain/schedule/entity/Schedule.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/scheduler/EmailScheduler.java
  src/main/java/com/gnims/project/scheduler/EventScheduler.java
  src/main/java/com/gnims/project/share/slack/SlackController.java
Labels: feature

#195 Feat #67 유저검색 수정
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
Labels: feature

#196 Feat #123 이메일 인증 수정
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/scheduler/EmailScheduler.java
  src/main/java/com/gnims/project/scheduler/EventScheduler.java
  src/main/java/com/gnims/project/share/gmail/EmailController.java
  src/main/java/com/gnims/project/share/gmail/EmailRepository.java
  src/main/java/com/gnims/project/share/gmail/EmailService.java
  src/main/java/com/gnims/project/share/gmail/EmailValidation.java
Labels: feature

#200 Test #197 회원 가입 동시 요청 테스트 케이스 수정
  src/test/java/com/gnims/project/domain/user/service/UserSignupConcurrentTest.java
Labels: test-code

#199 Feat #123 오류 수정
  src/main/java/com/gnims/project/share/gmail/EmailService.java
Labels: feature

#201 Test #197 회원 가입 동시 요청 테스트 케이스 수정
  src/test/java/com/gnims/project/domain/user/service/UserSignupConcurrentTest.java
Labels: fix

#202 Feat #193 4xx,5xx 에러 발생 시 슬랙 메시지로 전송 기능 추가
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/gnims/project/share/slack/SlackController.java
Labels: feature

#203 Feat/slack
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/gnims/project/scheduler/EmailScheduler.java
  src/main/java/com/gnims/project/scheduler/EventScheduler.java
  src/main/java/com/gnims/project/share/slack/SlackMessageSender.java
Labels: refactor, fix

#204 fix #193 커밋 충돌 해결
  src/main/java/com/gnims/project/scheduler/EmailScheduler.java
  src/main/java/com/gnims/project/scheduler/EventScheduler.java
Labels: fix
