Repository gnims-project/GNIMS-backend, pull requests merged in 2023-03, with the labels that each got.

#205 feat #57 일정 전체 조회 API 정렬 기능 추가 및 테스트 코드 작성
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/share/message/ExceptionMessage.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: feature, test-code

#206 Refactor/profile update
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/security/jwt/JwtUtil.java
  src/main/java/com/gnims/project/social/controller/SocialLoginController.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
Labels: refactor

#210 feat #144 알림 조회 API 개발
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/dto/ReadAllNotificationResponse.java
  src/main/java/com/gnims/project/domain/notification/dto/ReadNotificationResult.java
  src/main/java/com/gnims/project/domain/notification/dto/SimpleNotificationResult.java
  src/main/java/com/gnims/project/domain/notification/entity/Notification.java
  src/main/java/com/gnims/project/domain/notification/entity/NotificationType.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/share/message/ExceptionMessage.java
  src/main/java/com/gnims/project/share/message/ResponseMessage.java
Labels: feature

#212 fix #144 Notification -> User 의존으로 인한 delete 오류 해결
  src/test/java/com/gnims/project/domain/friendship/service/FollowTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleDeleteTest.java
  src/test/java/com/gnims/project/domain/schedule/service/SchedulePastTest.java
  src/test/java/com/gnims/project/domain/schedule/service/SchedulePendingTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleRejectTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleUpdateReadTest.java
Labels: bug, fix

#213 Feat, Test/notification
  src/main/java/com/gnims/project/domain/notification/dto/ReadAllNotificationResponse.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
Labels: feature, test-code

#214 Refactor/project
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/friendship/entity/Friendship.java
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/notification/dto/ReadAllNotificationResponse.java
  src/main/java/com/gnims/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneResponse.java
  src/main/java/com/gnims/project/domain/schedule/entity/Schedule.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/PasswordDto.java
  src/main/java/com/gnims/project/domain/user/dto/SignupRequestDto.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/gnims/project/security/jwt/JwtUtil.java
  src/main/java/com/gnims/project/share/gmail/EmailController.java
  src/main/java/com/gnims/project/share/gmail/EmailPasswordDto.java
  src/main/java/com/gnims/project/share/health/HealthCheckController.java
  src/main/java/com/gnims/project/share/message/ExceptionMessage.java
  src/main/java/com/gnims/project/share/message/ResponseMessage.java
  src/main/java/com/gnims/project/share/persistence/embedded/Appointment.java
  src/main/java/com/gnims/project/share/slack/SlackMessageSender.java
  src/test/java/com/gnims/project/HealthCheckTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleDeleteTest.java
  src/test/java/com/gnims/project/domain/schedule/service/SchedulePastTest.java
  src/test/java/com/gnims/project/domain/schedule/service/SchedulePendingTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleRejectTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleUpdateReadTest.java
  src/test/java/com/gnims/project/domain/user/service/PasswordUpdateTest.java
  src/test/java/com/gnims/project/domain/user/service/UserLoginTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSignupTest.java
Labels: refactor

#218 Test/user
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/test/java/com/gnims/project/domain/user/service/EmailCheckTest.java
  src/test/java/com/gnims/project/domain/user/service/ImageUploadTest.java
  src/test/java/com/gnims/project/domain/user/service/NicknameCheckTest.java
  src/test/java/com/gnims/project/domain/user/service/PasswordResetTest.java
  src/test/java/com/gnims/project/domain/user/service/PasswordUpdateTest.java
  src/test/java/com/gnims/project/domain/user/service/SocialSignupTest.java
  src/test/java/com/gnims/project/domain/user/service/UserLoginTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSearchTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSignupTest.java
Labels: test-code

#219 Feat/notifcation
  src/main/java/com/gnims/project/config/AsyncConfig.java
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendShipServiceResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResponse.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/dto/ReadNotificationResponse.java
  src/main/java/com/gnims/project/domain/notification/entity/Notification.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleServiceForm.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/scheduler/NotificationScheduler.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
Labels: feature, test-code, fix

#220 Feat #144 알림이 생성된 시간 순으로 내림차순 정렬
  src/main/java/com/gnims/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
Labels: feature

#222 Fix #144 알림 메시지에 닉네임으로 출력되던 현상 수정
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
Labels: fix

#223 Test/user
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/share/gmail/EmailService.java
  src/test/java/com/gnims/project/domain/user/service/PasswordResetTest.java
  src/test/java/com/gnims/project/domain/user/service/PasswordUpdateTest.java
Labels: test-code

#227 Chore/nginx : 이미지 업로드 문제 해결 시도
  .platform/nginx/nginx.conf
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/scheduler/EventScheduler.java
  src/main/java/com/gnims/project/scheduler/NotificationScheduler.java
  src/test/java/com/gnims/project/scheduler/SchedulerTest.java
Labels: feature

#228 release gnims service - verson 1.0.3
  .platform/nginx/nginx.conf
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/scheduler/EventScheduler.java
  src/main/java/com/gnims/project/scheduler/NotificationScheduler.java
  src/main/java/com/gnims/project/share/gmail/EmailService.java
  src/test/java/com/gnims/project/domain/user/service/PasswordResetTest.java
  src/test/java/com/gnims/project/domain/user/service/PasswordUpdateTest.java
  src/test/java/com/gnims/project/scheduler/SchedulerTest.java
Labels: release

#230 Chore #207 용량이 큰 이미지 업로드 문제 해결 시도2
  .platform/nginx/nginx.conf
Labels: fix

#231 hotfix gnims service - verson 1.0.3
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleRejectTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleUpdateReadTest.java
Labels: fix

#233 Chore #207 스크립트 수정 client_max_body_size 삭제
  .platform/nginx/nginx.conf
Labels: fix

#234 Chore #207 client_max_body_size 위치 수정
  .platform/nginx/nginx.conf
Labels: fix

#235 client_max_body_size 위치 수정
  .platform/nginx/nginx.conf
Labels: fix

#236 Fix/password reset
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: fix

#237 hotFix #39 팔로워 조회 API 잘못된 부분 수정
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
Labels: fix

#238 hotfix release gnims service - verson 1.0.4
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
Labels: fix

#240 Chore #207 그님스 서버로 리버스 프록시 설정
  .platform/nginx/nginx.conf
Labels: chore

#241 Feat/security
  .platform/nginx/nginx.conf
  src/main/java/com/gnims/project/ProjectApplication.java
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
Labels: feature, fix

#243 Feat/schedule
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleForm.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
Labels: test-code, fix

#244 release gnims service - verson 1.0.6
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleForm.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
Labels: release

#245 Refactor #94 주석 수정
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/SearchResponseDto.java
  src/main/java/com/gnims/project/share/gmail/EmailController.java
  src/main/java/com/gnims/project/share/gmail/EmailRepository.java
  src/main/java/com/gnims/project/share/gmail/EmailService.java
  src/main/java/com/gnims/project/social/controller/SocialLoginController.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
Labels: refactor

#248 Fix #247 에러 수정
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
Labels: fix

#249 release gnims service - verson 1.0.7
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
  src/main/java/com/gnims/project/domain/event/controller/EventController.java
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/PageScheduleResult.java
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/SearchResponseDto.java
  src/main/java/com/gnims/project/share/gmail/EmailController.java
  src/main/java/com/gnims/project/share/gmail/EmailRepository.java
  src/main/java/com/gnims/project/share/gmail/EmailService.java
  src/main/java/com/gnims/project/social/controller/SocialLoginController.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
Labels: fix, release

#250 Hotfix/schedule
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
Labels: fix

#251 hotfix gnims service - verson 1.0.8
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
Labels: fix, release

#253 Feature/schedule
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/gnims/project/share/message/ExceptionMessage.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
  src/test/java/com/gnims/project/domain/user/service/SocialSignupTest.java
Labels: test-code, fix

#254 release gnims service - verson 1.0.9
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/gnims/project/share/message/ExceptionMessage.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleCreateTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
  src/test/java/com/gnims/project/domain/user/service/SocialSignupTest.java
Labels: fix, release

#256 Fix/notification
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
Labels: fix

#257 release gnims service - verson 1.0.10
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
Labels: fix, release

#258 Feat/schedule
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadOneApiTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: fix

#259 release gnims service - verson 1.0.11
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadOneApiTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: test-code, release

#260 fix #252 팔로워 받지 않은 사람의 초대를 수락할 경우 조회되지 않는 현상 해결
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadOneApiTest.java
Labels: fix

#261 hotfix 1.0.12
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadOneApiTest.java
Labels: fix, release

#263 Feat/schedule
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/friendship/entity/Friendship.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadOneApiTest.java
Labels: feature, test-code

#264 [Feat/schedule] 일정 전체 조회 페이징 API 접근 가능 조건 반영 및 정렬 로직 개선
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: feature, fix

#265 release gnims service - verson 1.0.2
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/friendship/entity/Friendship.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadOneApiTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadTest.java
Labels: fix, release

#270 Refactor/domain
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/friendship/entity/Friendship.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/scheduler/EmailScheduler.java
  src/main/java/com/gnims/project/scheduler/EventScheduler.java
  src/main/java/com/gnims/project/share/message/ResponseMessage.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
Labels: feature, test-code, refactor

#271 release gnims service - verson 1.1.1
  src/main/java/com/gnims/project/config/WebSecurityConfig.java
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/friendship/entity/Friendship.java
  src/main/java/com/gnims/project/domain/friendship/exception/NotFriendshipException.java
  src/main/java/com/gnims/project/domain/friendship/repository/FriendshipRepository.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/exception/NotFoundInformationException.java
  src/main/java/com/gnims/project/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/gnims/project/exception/dto/ExceptionResponse.java
  src/main/java/com/gnims/project/exception/dto/ExceptionResponseMessage.java
  src/main/java/com/gnims/project/exception/dto/ExceptionResponses.java
  src/main/java/com/gnims/project/scheduler/EmailScheduler.java
  src/main/java/com/gnims/project/scheduler/EventScheduler.java
  src/main/java/com/gnims/project/security/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/gnims/project/share/message/ExceptionMessage.java
  src/main/java/com/gnims/project/share/message/ResponseMessage.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleDeleteTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleReadOneApiTest.java
  src/test/java/com/gnims/project/domain/user/service/SocialSignupTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSignupTest.java
Labels: release

#273 Fix/notification
  src/main/java/com/gnims/project/domain/friendship/dto/FollowReadResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendShipServiceResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResult.java
  src/main/java/com/gnims/project/domain/friendship/dto/PagingDataResponse.java
  src/main/java/com/gnims/project/domain/friendship/entity/FollowStatus.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/dto/ReadNotificationResponse.java
  src/main/java/com/gnims/project/domain/notification/dto/ReadNotificationResult.java
  src/main/java/com/gnims/project/domain/notification/dto/SimpleNotificationResult.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/domain/schedule/dto/PageScheduleResult.java
  src/main/java/com/gnims/project/domain/schedule/dto/PageableReadResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllUserDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneUserDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadPendingResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadScheduleResult.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleForm.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleServiceForm.java
  src/main/java/com/gnims/project/domain/schedule/dto/SimpleScheduleResult.java
  src/main/java/com/gnims/project/domain/user/dto/SearchPageableResult.java
  src/main/java/com/gnims/project/share/message/ExceptionMessage.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/SchedulePendingTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleRejectTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleUpdateReadTest.java
Labels: test-code, refactor

#275 Refactor/notification
  src/main/java/com/gnims/project/domain/notification/dto/NotificationForm.java
  src/main/java/com/gnims/project/domain/notification/entity/Notification.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
Labels: refactor

#276 release gnims service - verson 1.1.2
  README.md
  src/main/java/com/gnims/project/domain/friendship/dto/FollowReadResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendShipServiceResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResult.java
  src/main/java/com/gnims/project/domain/friendship/dto/PagingDataResponse.java
  src/main/java/com/gnims/project/domain/friendship/entity/FollowStatus.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/dto/NotificationForm.java
  src/main/java/com/gnims/project/domain/notification/dto/ReadNotificationResponse.java
  src/main/java/com/gnims/project/domain/notification/dto/ReadNotificationResult.java
  src/main/java/com/gnims/project/domain/notification/dto/SimpleNotificationResult.java
  src/main/java/com/gnims/project/domain/notification/entity/Notification.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/NotificationRepository.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/domain/schedule/dto/PageScheduleResult.java
  src/main/java/com/gnims/project/domain/schedule/dto/PageableReadResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllUserDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneUserDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadPendingResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadScheduleResult.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleForm.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleServiceForm.java
  src/main/java/com/gnims/project/domain/schedule/dto/SimpleScheduleResult.java
  src/main/java/com/gnims/project/domain/user/dto/SearchPageableResult.java
  src/main/java/com/gnims/project/share/message/ExceptionMessage.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleAcceptTest.java
  src/test/java/com/gnims/project/domain/schedule/service/SchedulePendingTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleRejectTest.java
  src/test/java/com/gnims/project/domain/schedule/service/ScheduleUpdateReadTest.java
Labels: release

#277 Refactor/notification
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/dto/FollowReadResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResponse.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/dto/NotificationForm.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleCreateController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadPendingResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleForm.java
  src/main/java/com/gnims/project/security/jwt/SecurityExceptionDto.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
  src/test/java/com/gnims/project/scheduler/SchedulerTest.java
Labels: refactor

#279 Refactor/user
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/EmailDto.java
  src/main/java/com/gnims/project/domain/user/dto/LoginResponseDto.java
  src/main/java/com/gnims/project/domain/user/dto/NicknameDto.java
  src/main/java/com/gnims/project/domain/user/dto/PasswordDto.java
  src/main/java/com/gnims/project/domain/user/dto/ProfileImageDto.java
  src/main/java/com/gnims/project/domain/user/dto/SearchAllQueryDto.java
  src/main/java/com/gnims/project/domain/user/dto/SearchResponseDto.java
  src/main/java/com/gnims/project/domain/user/dto/SimpleMessageResult.java
  src/main/java/com/gnims/project/domain/user/dto/UserResult.java
  src/main/java/com/gnims/project/domain/user/entity/SocialCode.java
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/scheduler/EmailScheduler.java
  src/main/java/com/gnims/project/security/jwt/JwtAuthFilter.java
  src/main/java/com/gnims/project/security/jwt/JwtUtil.java
  src/main/java/com/gnims/project/security/service/UserDetailsImpl.java
  src/main/java/com/gnims/project/security/service/UserDetailsServiceImpl.java
  src/main/java/com/gnims/project/share/email/AuthCodeDto.java
  src/main/java/com/gnims/project/share/email/EmailController.java
  src/main/java/com/gnims/project/share/email/EmailPasswordDto.java
  src/main/java/com/gnims/project/share/email/EmailRepository.java
  src/main/java/com/gnims/project/share/email/EmailService.java
  src/main/java/com/gnims/project/share/email/EmailValidation.java
  src/main/java/com/gnims/project/share/message/ResponseMessage.java
  src/main/java/com/gnims/project/share/validation/ValidationGroups.java
  src/main/java/com/gnims/project/social/controller/SocialLoginController.java
  src/main/java/com/gnims/project/social/dto/SocialEmailDto.java
  src/main/java/com/gnims/project/social/dto/SocialProfileDto.java
  src/main/java/com/gnims/project/social/dto/SocialResult.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
  src/test/java/com/gnims/project/domain/user/service/EmailCheckTest.java
  src/test/java/com/gnims/project/domain/user/service/ImageUploadTest.java
  src/test/java/com/gnims/project/domain/user/service/NicknameCheckTest.java
  src/test/java/com/gnims/project/domain/user/service/PasswordResetTest.java
  src/test/java/com/gnims/project/domain/user/service/PasswordUpdateTest.java
  src/test/java/com/gnims/project/domain/user/service/SocialSignupTest.java
  src/test/java/com/gnims/project/domain/user/service/UserLoginTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSearchTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSignupTest.java
  src/test/java/com/gnims/project/scheduler/SchedulerTest.java
Labels: test-code, refactor

#280 release gnims service - verson 1.1.3
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/dto/FollowReadResponse.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResponse.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/dto/NotificationForm.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleCreateController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadAllScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadOneScheduleDto.java
  src/main/java/com/gnims/project/domain/schedule/dto/ReadPendingResponse.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleForm.java
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/dto/EmailDto.java
  src/main/java/com/gnims/project/domain/user/dto/LoginResponseDto.java
  src/main/java/com/gnims/project/domain/user/dto/NicknameDto.java
  src/main/java/com/gnims/project/domain/user/dto/PasswordDto.java
  src/main/java/com/gnims/project/domain/user/dto/ProfileImageDto.java
  src/main/java/com/gnims/project/domain/user/dto/SearchAllQueryDto.java
  src/main/java/com/gnims/project/domain/user/dto/SearchResponseDto.java
  src/main/java/com/gnims/project/domain/user/dto/SimpleMessageResult.java
  src/main/java/com/gnims/project/domain/user/dto/UserResult.java
  src/main/java/com/gnims/project/domain/user/entity/SocialCode.java
  src/main/java/com/gnims/project/domain/user/repository/UserRepository.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/scheduler/EmailScheduler.java
  src/main/java/com/gnims/project/security/jwt/JwtAuthFilter.java
  src/main/java/com/gnims/project/security/jwt/JwtUtil.java
  src/main/java/com/gnims/project/security/jwt/SecurityExceptionDto.java
  src/main/java/com/gnims/project/security/service/UserDetailsImpl.java
  src/main/java/com/gnims/project/security/service/UserDetailsServiceImpl.java
  src/main/java/com/gnims/project/share/email/AuthCodeDto.java
  src/main/java/com/gnims/project/share/email/EmailController.java
  src/main/java/com/gnims/project/share/email/EmailPasswordDto.java
  src/main/java/com/gnims/project/share/email/EmailRepository.java
  src/main/java/com/gnims/project/share/email/EmailService.java
  src/main/java/com/gnims/project/share/email/EmailValidation.java
  src/main/java/com/gnims/project/share/message/ResponseMessage.java
  src/main/java/com/gnims/project/share/validation/ValidationGroups.java
  src/main/java/com/gnims/project/social/controller/SocialLoginController.java
  src/main/java/com/gnims/project/social/dto/SocialEmailDto.java
  src/main/java/com/gnims/project/social/dto/SocialProfileDto.java
  src/main/java/com/gnims/project/social/dto/SocialResult.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
  src/test/java/com/gnims/project/domain/user/service/EmailCheckTest.java
  src/test/java/com/gnims/project/domain/user/service/ImageUploadTest.java
  src/test/java/com/gnims/project/domain/user/service/NicknameCheckTest.java
  src/test/java/com/gnims/project/domain/user/service/PasswordResetTest.java
  src/test/java/com/gnims/project/domain/user/service/PasswordUpdateTest.java
  src/test/java/com/gnims/project/domain/user/service/SocialSignupTest.java
  src/test/java/com/gnims/project/domain/user/service/UserLoginTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSearchTest.java
  src/test/java/com/gnims/project/domain/user/service/UserSignupTest.java
  src/test/java/com/gnims/project/scheduler/SchedulerTest.java
Labels: release

#281 Feat/schedule
  src/main/java/com/gnims/project/domain/event/controller/EventController.java
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
Labels: feature, refactor

#282 hotfix
  src/main/java/com/gnims/project/domain/event/controller/EventController.java
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
Labels: fix

#283 Feat #39 알림 수락/거절 기능 추가
  src/main/java/com/gnims/project/domain/notification/entity/NotificationType.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleDecisionEventForm.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
Labels: feature

#284 release
  src/main/java/com/gnims/project/domain/notification/entity/NotificationType.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleDecisionEventForm.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
Labels: feature, release

#285 Feat #39 알림 수락/거절 리팩토링
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleDecisionEventForm.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
Labels: feature

#286 hotfix
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleDecisionEventForm.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
Labels: release

#287 hotfix - 페이징 처리 시 스케줄이 중복해서 나오는 오류 해결
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
Labels: fix

#288 Feat #39 스케줄 페이징 처리 invitees 가 안나오는 오류 수정
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
Labels: fix

#289 fix #144 알림 오류 수정
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
Labels: fix

#291 Feat/schedule
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendShipCreatedEvent.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResponse.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleCreatedEvent.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleForm.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleInviteRepliedEvent.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/share/persistence/embedded/Appointment.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
Labels: fix

#292 fix #3 로그인 실패 시 401 -> 400 에러로 수정
  src/test/java/com/gnims/project/domain/user/service/UserLoginTest.java
Labels: fix

#293 hotfix
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
Labels: fix

#295 Feat/notification
  src/main/java/com/gnims/project/domain/event/entity/Event.java
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendShipCreatedEvent.java
  src/main/java/com/gnims/project/domain/friendship/dto/FriendshipResponse.java
  src/main/java/com/gnims/project/domain/notification/dto/NotificationForm.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/repository/SseEmitterManager.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleCreatedEvent.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleForm.java
  src/main/java/com/gnims/project/domain/schedule/dto/ScheduleInviteRepliedEvent.java
  src/main/java/com/gnims/project/domain/schedule/dto/SimpleScheduleResult.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/security/service/UserDetailsImpl.java
  src/main/java/com/gnims/project/share/persistence/embedded/Appointment.java
  src/main/java/com/gnims/project/share/persistence/superclass/Auditor.java
  src/test/java/com/gnims/project/domain/notification/service/NotificationApiTest.java
  src/test/java/com/gnims/project/domain/user/service/UserLoginTest.java
Labels: fix, improvement

#297 Refactor/user
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/exception/dto/AuthenticationCodeValidityException.java
  src/main/java/com/gnims/project/share/email/EmailController.java
  src/main/java/com/gnims/project/share/email/EmailService.java
  src/main/java/com/gnims/project/share/message/ResponseMessage.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
Labels: refactor

#298 Refactor #294 일정 생성 로직 개선 create() 메소드 통일
  src/main/java/com/gnims/project/domain/notification/dto/NotificationForm.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
Labels: feature

#303 release gnims service - verson 1.1.5
  README.md
  src/main/java/com/gnims/project/domain/friendship/controller/FriendshipController.java
  src/main/java/com/gnims/project/domain/friendship/dto/FollowIntegratedResponse.java
  src/main/java/com/gnims/project/domain/notification/controller/NotificationController.java
  src/main/java/com/gnims/project/domain/notification/dto/NotificationAbstractForm.java
  src/main/java/com/gnims/project/domain/notification/dto/NotificationAllForm.java
  src/main/java/com/gnims/project/domain/notification/dto/NotificationForm.java
  src/main/java/com/gnims/project/domain/notification/entity/Notification.java
  src/main/java/com/gnims/project/domain/notification/listener/AlarmEventListener.java
  src/main/java/com/gnims/project/domain/notification/service/NotificationService.java
  src/main/java/com/gnims/project/domain/schedule/controller/ScheduleController.java
  src/main/java/com/gnims/project/domain/schedule/dto/SimpleScheduleResult.java
  src/main/java/com/gnims/project/domain/user/controller/UserController.java
  src/main/java/com/gnims/project/domain/user/service/UserService.java
  src/main/java/com/gnims/project/exception/dto/AuthenticationCodeValidityException.java
  src/main/java/com/gnims/project/security/service/UserDetailsImpl.java
  src/main/java/com/gnims/project/share/email/EmailController.java
  src/main/java/com/gnims/project/share/email/EmailService.java
  src/main/java/com/gnims/project/share/message/ResponseMessage.java
  src/main/java/com/gnims/project/share/persistence/superclass/Auditor.java
  src/main/java/com/gnims/project/social/sevice/KakaoService.java
  src/main/java/com/gnims/project/social/sevice/NaverService.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowerTest.java
  src/test/java/com/gnims/project/domain/friendship/service/FollowingTest.java
Labels: release

#305 Chore #304 업스트림 서버 IP 변경
  .platform/nginx/nginx.conf
Labels: chore

#307 Chore #304 업스트림 서버 IP 재변경
  .platform/nginx/nginx.conf
Labels: chore

#313 Improvement/transaction
  src/main/java/com/gnims/project/domain/friendship/service/FriendshipService.java
  src/main/java/com/gnims/project/domain/schedule/service/ScheduleService.java
  src/main/java/com/gnims/project/log/advice/ReadOnlyTransactionCheckAspect.java
Labels: improvement
